{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rancherchart.serviceAccountName" . }}
  labels:
{{ include "rancherchart.labels" . | indent 4 }}
{{- end -}}
